### ISSUE TITLE
Doesn't work on BigNumber class

### ISSUE THREAD

**Issue by xluckydegen** [shaochuancs/esserializer#119]
Hi,
i'm testing your library and everything works fine on my own classes, but I'm not able to make it work with BigNumber library.

```
    esserializer.registerClasses([BigNumber]);
    const val = BnUtils.toBigNumber(42, 0);
    let buf = esserializer.serialize(val);
    let output = esserializer.deserialize(buf);
    expect(output.toNumber()).equal(42);
```

the buffer is: `{"type":"BigNumber","hex":"0x2a"}'`

There is no `ess_cn` property like in my other test classes: `'{"person":{"name":"a","age":2,"ess_cn":"TestPerson"}}'`

Is there anything I can do wit that? 

Is this what solves the PRO version?

PS: The same for Big class

**Comment by shaochuancs** [comment]
Thanks @xluckydegen for your feedback. This is a bug in esserializer which does not ignore custom `toJSON` method defined in BigNumber class.

I've fixed this bug and published a new version (1.3.9). Please let me know if you get other problems working with BigNumber library.

**Comment by xluckydegen** [comment]
Thanks, BigNumber now working great, but "Big" serialization is still broken.

```
import { Big } from "big.js";

const val : Big = Big(42);
esserializer.registerClasses([Big]);
const buf = esserializer.serialize(val);
const output = esserializer.deserialize(buf);
expect(output.toNumber()).equal(42);
```

Big is serialized as `'{"s":1,"e":1,"c":[4,2]}'`

**Comment by shaochuancs** [comment]
Hi, @xluckydegen 

The compatibility issue with big.js has been fixed. Please check esserializer v1.3.10

Thanks
Chuan

**Comment by xluckydegen** [comment]
Thank you for prompt response. 1.3.10 is working great!

**Comment by shaochuancs** [comment]
Thanks @xluckydegen for your feedback. I'll close this issue now.
